#test puroposgite DB
#spring.datasource.url=jdbc:postgresql://localhost:5432/BankSystemTest
#spring.datasource.username=postgres
#spring.datasource.password=root
#spring.datasource.driver-class-name=org.postgresql.Driver
#
#spring.jpa.hibernate.ddl-auto=create-drop
#spring.jpa.show-sql=false
#logging.level.root=WARN
#spring.sql.init.mode=never