#test purposive DB
spring.config.activate.on-profile=test
spring.datasource.url=jdbc:postgresql://localhost:5432/BankSystem
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver
server.port=8082

spring.flyway.clean-disabled=true

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false
logging.level.root=WARN
spring.sql.init.mode=never

jwt.secret=LjUKbLecheh8I0XWzsfDrkdKVGfZB73Jx441RrmGaRr